# Use the official Node.js 18 image.
# https://hub.docker.com/_/node
FROM node:latest

# Increase memory limit (adjust as needed)
ENV NODE_OPTIONS="--max-old-space-size=4096"

# Create and change to the app directory.
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy local code to the container
COPY . .

# # Build the application
# RUN npm run build

# Run the application
CMD ["npm", "run dev"]
