# Generated by Django 5.0.2 on 2024-03-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=400, null=True)),
                ('key', models.IntegerField(default=1)),
                ('colorfrom', models.CharField(blank=True, max_length=100, null=True)),
                ('colorto', models.CharField(blank=True, max_length=100, null=True)),
                ('likes', models.CharField(blank=True, max_length=100, null=True)),
                ('github_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
