# Generated by Django 4.2.10 on 2024-03-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicatedata',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='replicatedata',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='replicatedata',
            name='owner',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='replicatedata',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='replicatedata',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='replicatedata',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
