# Generated by Django 4.2.10 on 2024-03-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicate', '0002_replicatedata_description_replicatedata_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replicatedata',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='replicatedata',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='replicatedata',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='replicatedata',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='replicatedata',
            name='run_count',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='replicatedata',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
