# Generated by Django 4.2.10 on 2024-03-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicate', '0003_alter_replicatedata_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicatedata',
            name='key',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
