# Generated by Django 4.2.10 on 2024-03-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicate', '0006_alter_replicatedata_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replicatedata',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='replicatedata',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='replicatedata',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replicatedata',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='replicatedata',
            name='url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
