# Generated by Django 5.0.2 on 2024-03-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicate', '0008_rename_run_count_replicatedata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replicatedata',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
