# Generated by Django 5.0.2 on 2024-03-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicate', '0009_alter_replicatedata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicatedata',
            name='colorfrom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='replicatedata',
            name='colorto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='replicatedata',
            name='likes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
