# Generated by Django 5.0.2 on 2024-03-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicate', '0010_replicatedata_colorfrom_replicatedata_colorto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicatedata',
            name='github_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
