# Generated by Django 4.2.6 on 2023-11-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0014_bookdemomodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="workspace_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="TextBlockModel",
            fields=[
                ("blockId", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_analysis.workspace"),
                ),
            ],
        ),
    ]
