# Generated by Django 4.2.6 on 2023-10-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mail_verify",
            field=models.BooleanField(default=False),
        ),
    ]
