# Generated by Django 4.2.6 on 2024-02-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_mail_verify"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data_url",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="path",
            field=models.FileField(blank=True, null=True, upload_to="dataurl", verbose_name="upload Field"),
        ),
    ]
