# Generated by Django 4.2.6 on 2023-10-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("dashboard_id", models.AutoField(primary_key=True, serialize=False)),
                ("dashboard_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DataProduct",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                ("product_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                ("metric_id", models.AutoField(primary_key=True, serialize=False)),
                ("metric_name", models.CharField(max_length=255)),
                ("metric_configuration", models.TextField()),
                ("likes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="MetricComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                ("space_id", models.AutoField(primary_key=True, serialize=False)),
                ("space_name", models.CharField(max_length=255)),
                ("space_description", models.TextField()),
                ("space_url", models.CharField(max_length=255)),
                ("archived", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=255)),
                ("team_description", models.TextField()),
                ("team_logo", models.ImageField(blank=True, null=True, upload_to="team_logos/")),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("team_member_id", models.AutoField(primary_key=True, serialize=False)),
                ("member_role", models.CharField(choices=[("Admin", "Admin"), ("Member", "Member")], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                ("workflow_id", models.AutoField(primary_key=True, serialize=False)),
                ("workflow_name", models.CharField(max_length=255)),
                ("workflow_status", models.CharField(max_length=255)),
                ("alert_flag", models.BooleanField(default=False)),
            ],
        ),
    ]
