# Generated by Django 4.2.6 on 2023-10-09 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="reviewed_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="teammember",
            name="member_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="teammember",
            name="team_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_analysis.team"),
        ),
        migrations.AddField(
            model_name="team",
            name="admin_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="space",
            name="edit_permissions",
            field=models.ManyToManyField(related_name="edit_permissions", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="project",
            name="team_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_analysis.team"),
        ),
        migrations.AddField(
            model_name="project",
            name="user_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="metriccomment",
            name="metric",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_analysis.metric"),
        ),
        migrations.AddField(
            model_name="metriccomment",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="metric",
            name="comments",
            field=models.ManyToManyField(
                related_name="metric_comments", through="data_analysis.MetricComment", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="refined_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="metric",
            name="tags",
            field=models.ManyToManyField(related_name="metric_tags", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="dataproduct",
            name="uploaded_data_sources",
            field=models.ManyToManyField(related_name="uploaded_data_sources", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="metrics_used",
            field=models.ManyToManyField(to="data_analysis.metric"),
        ),
    ]
