# Generated by Django 4.2.6 on 2023-10-24 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0006_workspace_created_at_workspace_deleted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUrlModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_url", models.CharField(max_length=255)),
                (
                    "workspace_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data_analysis.workspace"),
                ),
            ],
        ),
    ]
