# Generated by Django 4.2.6 on 2023-10-30 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0009_blockmodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlockModel",
            new_name="PythonBlockModel",
        ),
    ]
