# Generated by Django 4.2.6 on 2023-11-10 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0012_contactus"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactUs",
            new_name="ContactUsModel",
        ),
    ]
