# Generated by Django 4.2.6 on 2023-11-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0016_pythonblockmodel_chart_pythonblockmodel_metric_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pythonblockmodel",
            old_name="text",
            new_name="header",
        ),
        migrations.AddField(
            model_name="pythonblockmodel",
            name="semiheader",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pythonblockmodel",
            name="smallHeader",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pythonblockmodel",
            name="spanText",
            field=models.TextField(null=True),
        ),
    ]
