# Generated by Django 4.2.6 on 2023-11-20 01:28

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0018_alter_pythonblockmodel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pythonblockmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("sql", "SQL"),
                    ("metric", "Metric"),
                    ("chart", "Chart"),
                    ("table", "Table"),
                    ("heading1", "Heading1"),
                    ("heading2", "Heading2"),
                    ("heading3", "Heading3"),
                    ("paragraph", "Paragraph"),
                ],
                default="python",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="workspace_name",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
