# Generated by Django 4.2.6 on 2023-11-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0019_alter_pythonblockmodel_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="workspace_name",
            field=models.CharField(max_length=255),
        ),
    ]
