# Generated by Django 4.2.6 on 2023-11-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0024_rename_pythonblockmodel_blockmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataConnectionModel",
            fields=[
                ("connectionId", models.AutoField(primary_key=True, serialize=False)),
                ("connectionname", models.CharField(max_length=255)),
                ("connectiontype", models.CharField(max_length=255)),
                ("connectionstatus", models.CharField(max_length=255)),
                ("connectioncreateuser", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
