# Generated by Django 4.2.6 on 2023-12-04 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0028_alter_dataconnectionmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataconnectionmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 12, 4, 10, 48, 19, 682305, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dataconnectionmodel",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=datetime.datetime(2023, 12, 4, 10, 48, 25, 337654, tzinfo=datetime.timezone.utc)
            ),
            preserve_default=False,
        ),
    ]
