# Generated by Django 4.2.6 on 2023-12-04 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0030_remove_dataconnectionmodel_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataconnectionmodel",
            name="deleted_at",
        ),
        migrations.AddField(
            model_name="dataconnectionmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataconnectionmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
