# Generated by Django 4.2.6 on 2023-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0031_remove_dataconnectionmodel_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataconnectionmodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
