# Generated by Django 4.2.6 on 2023-12-06 02:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0032_dataconnectionmodel_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataurlmodel",
            name="workspace_id",
        ),
    ]
