# Generated by Django 4.2.6 on 2023-12-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0033_remove_dataurlmodel_workspace_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataconnectionmodel",
            name="connection_data",
            field=models.JSONField(null=True),
        ),
    ]
