# Generated by Django 4.2.6 on 2023-12-21 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_analysis", "0034_dataconnectionmodel_connection_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentModel",
            fields=[
                ("commentId", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "userId",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
