# Generated by Django 4.2.6 on 2024-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0037_commentmodel_blockid"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionRecordModel",
            fields=[
                ("transactionId", models.AutoField(primary_key=True, serialize=False)),
                ("payType", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("destinationAddress", models.CharField(max_length=100)),
                ("txHash", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
