# Generated by Django 4.2.6 on 2024-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0038_transactionrecordmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionrecordmodel",
            name="amount",
            field=models.FloatField(),
        ),
    ]
