# Generated by Django 4.2.6 on 2024-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginUserWalletAddress",
            fields=[
                ("walletId", models.AutoField(primary_key=True, serialize=False)),
                ("walletAddress", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionRecordModel",
            fields=[
                ("transactionId", models.AutoField(primary_key=True, serialize=False)),
                ("payType", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                ("destinationAddress", models.CharField(max_length=100)),
                ("txHash", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Dashboard",
        ),
        migrations.DeleteModel(
            name="DataProduct",
        ),
        migrations.DeleteModel(
            name="Metric",
        ),
        migrations.DeleteModel(
            name="MetricComment",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Space",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="TeamMember",
        ),
        migrations.DeleteModel(
            name="Workflow",
        ),
    ]
