# Generated by Django 4.2.6 on 2024-02-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionRecordModel",
            fields=[
                ("transactionId", models.AutoField(primary_key=True, serialize=False)),
                ("payType", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                ("destinationAddress", models.CharField(max_length=100)),
                ("txHash", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="dataproduct",
            name="uploaded_data_sources",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="refined_by",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="metriccomment",
            name="metric",
        ),
        migrations.RemoveField(
            model_name="metriccomment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="project",
            name="team_id",
        ),
        migrations.RemoveField(
            model_name="project",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="space",
            name="edit_permissions",
        ),
        migrations.RemoveField(
            model_name="team",
            name="admin_id",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="member_id",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="team_id",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="reviewed_by",
        ),
        migrations.DeleteModel(
            name="Dashboard",
        ),
        migrations.DeleteModel(
            name="DataProduct",
        ),
        migrations.DeleteModel(
            name="Metric",
        ),
        migrations.DeleteModel(
            name="MetricComment",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Space",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="TeamMember",
        ),
        migrations.DeleteModel(
            name="Workflow",
        ),
    ]
