# Generated by Django 4.2.6 on 2023-11-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0015_workspace_workspace_title_textblockmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythonblockmodel",
            name="chart",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pythonblockmodel",
            name="metric",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pythonblockmodel",
            name="sql",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pythonblockmodel",
            name="table",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pythonblockmodel",
            name="text",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="pythonblockmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("sql", "SQL"),
                    ("metric", "Metric"),
                    ("chart", "Chart"),
                    ("table", "Table"),
                    ("text", "Text"),
                ],
                default="python",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="workspace_title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
