# Generated by Django 4.2.6 on 2023-11-22 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0023_remove_pythonblockmodel_python_code_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PythonBlockModel",
            new_name="BlockModel",
        ),
    ]
