# Generated by Django 4.2.6 on 2023-11-28 18:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0025_dataconnectionmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataconnectionmodel",
            name="connectionusedin",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), null=True, size=None
            ),
        ),
    ]
