# Generated by Django 4.2.6 on 2023-12-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0036_remove_commentmodel_userid_commentmodel_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="blockId",
            field=models.IntegerField(null=True),
        ),
    ]
