# Generated by Django 4.2.6 on 2023-11-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0020_alter_workspace_workspace_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_name",
        ),
        migrations.AddField(
            model_name="project",
            name="encrypted_project_name",
            field=models.BinaryField(default=b""),
        ),
    ]
