# Generated by Django 4.2.6 on 2023-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0022_remove_workspace_workspace_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pythonblockmodel",
            name="python_code",
        ),
        migrations.AddField(
            model_name="pythonblockmodel",
            name="encrypted_python_code",
            field=models.BinaryField(default=b""),
        ),
    ]
