# Generated by Django 4.2.6 on 2023-12-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_analysis", "0027_dataconnectionmodel_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataconnectionmodel",
            name="created_at",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dataconnectionmodel",
            name="updated_at",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
